spring:
  profiles:
    active: local

  datasource:
    url: jdbc:mysql://localhost:3306/authentication
    username: catsriding
    password: catsriding

  jpa:
    database: mysql
    open-in-view: false
    generate-ddl: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
    hibernate:
      ddl-auto: validate